### ISSUE TITLE
PDF::Builder support

### ISSUE THREAD

**Issue by PhilterPaper** [ctrlo/CtrlO-PDF#6]
Two things to consider:

1. Would it be possible to give a user the choice between using PDF::API2 and PDF::Builder? I think you'll find the latter much improved. Perhaps which system could be passed in as a parameter, or an optional flag (default to one or the other).
2. PDF::Table 1.001 was just released. It works with either PDF::API2 or PDF::Builder. Note that there were a few changes that may affect CtrlO-PDF, such as default padding increasing from 0 to 2pt. If this creates any problems, you may want to explicitly set padding to 0 (if not overridden by the user), or use the compatibility feature.

**Comment by abeverley** [comment]
Thanks. I'm certainly happy with (1) in principle, but don't really have the time at the moment to look into it. Are you interested in submitting a PR?

Thanks for pointing out (2), I didn't realise that. Good question about the compatibility. I'll see if it affects any of my projects and take things from there.

**Comment by PhilterPaper** [comment]
I can't commit right now to a PR to add PDF::Builder capability, but I'll think about it, and maybe can start looking at it soon (getting Builder release 3.020 out the door must take priority).

**Comment by PhilterPaper** [comment]
I just sent PR #7 to level-set the stage for PDF::Builder support work, once you have merged that request (and suggest closing PR #5).

**Comment by PhilterPaper** [comment]
I think I have it working, but ran into one problem. You use PDF::TextBlock to do your text, and it's hard-wired to expect PDF::API2 (even though you pass in the PDF object to use!). I suggested a one-line change to fix it. We'll have to see if the owner is willing to do this, and if so, when they get the next PDF::TextBlock release out.

If they're not willing to update their product, that leaves you with the option to either have users manually patch their PDF::TextBlock file, or to write your own version of this package and include it with CtrlO::PDF. Otherwise, you are blocked from using PDF::Builder.  :-(

**Comment by PhilterPaper** [comment]
BTW, that's RT 133974 against PDF::TextBlock, if you want to follow that issue.

**Comment by PhilterPaper** [comment]
Jay says he would be happy to add support for PDF::Builder to PDF::TextBlock, so I should be able to issue a PR against CtrlO::PDF fairly soon.

**Comment by abeverley** [comment]
Brilliant, thanks for the update @PhilterPaper and for your work on this.

**Comment by PhilterPaper** [comment]
You may want to keep an eye on this discussion: https://github.com/jhannah/pdf-textblock/issues/6 . It seems that both CtrlO::PDF and PDF::TextBlock currently prereq PDF::API2 for testing, although neither really requires it for the base installation. Removing the prereq for PDF::API2 would permit the installation of CtrlO::PDF _without_ either PDF::API2 or PDF::Builder, which would result in either a test failure or a test skip. It may be possible in Makefile.PL to see if one is already there, and if not, go ahead and prereq one of them. Then the tests themselves check which one to use (in a preferred order), knowing that at least one of them will be present.

**Comment by PhilterPaper** [comment]
I have created a PR against PDF::TextBlock, to permit it to work with PDF::Builder. Once that is merged and available on CPAN, I will create a PR against CtrlO::PDF to do likewise. The code is ready, if you want to look at PhilterPaper/CtrlO-PDF to start getting a feel for it.

**Comment by PhilterPaper** [comment]
Even though there are some minor packaging issues with the latest PDF::TextBlock (I expect release 0.13 to fix them), it will still work with both PDF::API2 and PDF::Builder. Therefore I have pushed out a PR against CtrlO::PDF to support PDF::Builder. Come to think of it, you might want to adjust the prereqs list in CtrlO::PDF's Makefile.PL to require at least version 0.12 of PDF::TextBlock, rather than 0 ("any"). If 0.13 is released before you get to that, 0.13 should be the minimum.

**Comment by PhilterPaper** [comment]
Per #8, PDF::TextBlock appears to work correctly now, and you can proceed with updating CtrlO::PDF at any time. Thank you for your attention to this; it's good to have PDF::Builder support.
